/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ybalcon.gestform.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import org.ybalcon.gestform.Dao.ConnectDb;

import org.ybalcon.gestform.Dao.FormationDao;
import org.ybalcon.gestform.Dao.StagiaireDao;
import org.ybalcon.gestform.GestForm;
import sun.applet.Main;

/**
 *
 * @author ybalcon
 */
public class Frame extends javax.swing.JFrame {

    TblStagiaire tbls;
    TblFormation tblf;

    public void emptyFieldWarning(String champs) {
        JOptionPane jpWarning = new JOptionPane();
        jpWarning.showMessageDialog(null, "Champs requis : " + champs, "Champs requis", JOptionPane.WARNING_MESSAGE);

    }

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();

        List<Formation> formations = FormationDao.findAll();
        for (Formation f : formations) {
            comboAddStagiaire.addItem(f);
        }
        btnDelFormation.setEnabled(false);
        btnEditFormation.setEnabled(false);
        btnEditStagiaire.setEnabled(false);
        btnDelStagiaire.setEnabled(false);
        AddStagPanel.setVisible(false);
        editStagPanel.setVisible(false);
        addEcfPanel.setVisible(false);
        editEcfPanel.setVisible(false);

        TableauFormation.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {

                btnEditFormation.setEnabled(true);
                btnDelFormation.setEnabled(true);

            }
        });
        TableauStagiaire.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                btnEditStagiaire.setEnabled(true);
                btnDelStagiaire.setEnabled(true);
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("java?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableauFormation = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        btnAddFormation = new javax.swing.JButton();
        btnEditFormation = new javax.swing.JButton();
        btnDelFormation = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        btnAddStagiaire = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableauStagiaire = new javax.swing.JTable();
        AddStagPanel = new javax.swing.JPanel();
        textFieldAddPrenom = new javax.swing.JTextField();
        textFieldAddNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAddStagiaire = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnConfirmAddStagiaire = new javax.swing.JButton();
        btnEraseAddStagiaire = new javax.swing.JButton();
        btnCancelAddStagiaire = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnEditStagiaire = new javax.swing.JButton();
        btnDelStagiaire = new javax.swing.JButton();
        editStagPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textFieldEditPrenom = new javax.swing.JTextField();
        textFieldEditNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboEditStagiaire = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        btnConfirmEditStagiaire = new javax.swing.JButton();
        btnCancelEditStagiaire = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnAddEcf = new javax.swing.JButton();
        btnEditEcf = new javax.swing.JButton();
        btnDelEcf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addEcfPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editEcfPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestForm 1.0.2");
        setName("Ma fenetre"); // NOI18N

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setName("GestForm 1.0.2"); // NOI18N

        jScrollPane1.setViewportView(TableauFormation);
        tblf = new TblFormation(FormationDao.findAll());
        TableauFormation.setModel(tblf);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        btnAddFormation.setText("Ajouter");
        btnAddFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFormationActionPerformed(evt);
            }
        });
        jPanel9.add(btnAddFormation);

        btnEditFormation.setText("Modifier");
        btnEditFormation.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEditFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFormationActionPerformed(evt);
            }
        });
        jPanel9.add(btnEditFormation);

        btnDelFormation.setText("Supprimer");
        btnDelFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelFormationActionPerformed(evt);
            }
        });
        jPanel9.add(btnDelFormation);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1))
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Formations", jPanel2);

        btnAddStagiaire.setText("Ajouter un(e) stagiaire");
        btnAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStagiaireActionPerformed(evt);
            }
        });

        tbls = new TblStagiaire(StagiaireDao.findAll());
        jScrollPane2.setViewportView(TableauStagiaire);
        TableauStagiaire.setModel(tbls);

        textFieldAddPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAddPrenomActionPerformed(evt);
            }
        });

        textFieldAddNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAddNomActionPerformed(evt);
            }
        });

        jLabel1.setText("Prénom");

        jLabel2.setText("Nom");

        comboAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAddStagiaireActionPerformed(evt);
            }
        });

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        btnConfirmAddStagiaire.setText("OK");
        btnConfirmAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddStagiaireActionPerformed(evt);
            }
        });
        jPanel13.add(btnConfirmAddStagiaire);

        btnEraseAddStagiaire.setText("Effacer");
        btnEraseAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseAddStagiaireActionPerformed(evt);
            }
        });
        jPanel13.add(btnEraseAddStagiaire);

        btnCancelAddStagiaire.setText("Annuler");
        btnCancelAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddStagiaireActionPerformed(evt);
            }
        });
        jPanel13.add(btnCancelAddStagiaire);

        javax.swing.GroupLayout AddStagPanelLayout = new javax.swing.GroupLayout(AddStagPanel);
        AddStagPanel.setLayout(AddStagPanelLayout);
        AddStagPanelLayout.setHorizontalGroup(
            AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(106, 106, 106)
                .addGroup(AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAddStagiaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldAddPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldAddNom)
                    .addGroup(AddStagPanelLayout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStagPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AddStagPanelLayout.setVerticalGroup(
            AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStagPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAddPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(AddStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAddNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addComponent(comboAddStagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        btnEditStagiaire.setText("Modifier");
        btnEditStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStagiaireActionPerformed(evt);
            }
        });
        jPanel10.add(btnEditStagiaire);

        btnDelStagiaire.setText("Supprimer");
        btnDelStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStagiaireActionPerformed(evt);
            }
        });
        jPanel10.add(btnDelStagiaire);

        jLabel6.setText("Prénom");

        textFieldEditPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEditPrenomActionPerformed(evt);
            }
        });

        jLabel7.setText("Nom");

        btnConfirmEditStagiaire.setText("OK");

        btnCancelEditStagiaire.setText("Annuler");
        btnCancelEditStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditStagiaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(btnConfirmEditStagiaire)
                .addGap(0, 0, 0)
                .addComponent(btnCancelEditStagiaire))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmEditStagiaire)
            .addComponent(btnCancelEditStagiaire)
        );

        jLabel3.setText("Modification de stagiaire");

        javax.swing.GroupLayout editStagPanelLayout = new javax.swing.GroupLayout(editStagPanel);
        editStagPanel.setLayout(editStagPanelLayout);
        editStagPanelLayout.setHorizontalGroup(
            editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editStagPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editStagPanelLayout.createSequentialGroup()
                        .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboEditStagiaire, 0, 260, Short.MAX_VALUE)
                                .addComponent(textFieldEditNom)
                                .addComponent(textFieldEditPrenom)))))
                .addContainerGap())
        );
        editStagPanelLayout.setVerticalGroup(
            editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStagPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEditPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(editStagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEditNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(comboEditStagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToggleButton1.setText("Generer un état");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddStagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddStagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editStagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddStagiaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddStagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editStagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jToggleButton1)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stagiaires", jPanel5);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btnAddEcf.setText("Ajouter");
        btnAddEcf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEcfActionPerformed(evt);
            }
        });
        jPanel8.add(btnAddEcf);

        btnEditEcf.setText("Modifier");
        btnEditEcf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEcfActionPerformed(evt);
            }
        });
        jPanel8.add(btnEditEcf);

        btnDelEcf.setText("Supprimer");
        jPanel8.add(btnDelEcf);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel4.setText("Ajouter un ECF");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("Validé");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nom de l'ecf");

        jLabel8.setText("Formation");

        jLabel9.setText("Stagiaire");

        jPanel11.setLayout(new java.awt.GridLayout());

        jButton1.setText("jButton1");
        jPanel11.add(jButton1);

        jButton2.setText("jButton2");
        jPanel11.add(jButton2);

        jButton3.setText("jButton3");
        jPanel11.add(jButton3);

        javax.swing.GroupLayout addEcfPanelLayout = new javax.swing.GroupLayout(addEcfPanel);
        addEcfPanel.setLayout(addEcfPanelLayout);
        addEcfPanelLayout.setHorizontalGroup(
            addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEcfPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEcfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEcfPanelLayout.createSequentialGroup()
                        .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 150, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        addEcfPanelLayout.setVerticalGroup(
            addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEcfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(addEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );

        jLabel10.setText("Modifier un ECF");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox2.setText("Validé");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nom de l'ecf");

        jLabel12.setText("Formation");

        jLabel13.setText("Stagiaire");

        jPanel15.setLayout(new java.awt.GridLayout());

        jButton4.setText("jButton4");
        jPanel15.add(jButton4);

        jButton6.setText("jButton6");
        jPanel15.add(jButton6);

        jButton5.setText("jButton5");
        jPanel15.add(jButton5);

        javax.swing.GroupLayout editEcfPanelLayout = new javax.swing.GroupLayout(editEcfPanel);
        editEcfPanel.setLayout(editEcfPanelLayout);
        editEcfPanelLayout.setHorizontalGroup(
            editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEcfPanelLayout.createSequentialGroup()
                .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editEcfPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox4, 0, 150, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(editEcfPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        editEcfPanelLayout.setVerticalGroup(
            editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEcfPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(editEcfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addEcfPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(editEcfPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addEcfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editEcfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(386, 386, 386))
        );

        jTabbedPane1.addTab("ECF", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStagiaireActionPerformed
        AddStagPanel.setVisible(true);

    }//GEN-LAST:event_btnAddStagiaireActionPerformed

    private void btnEditFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFormationActionPerformed
        JOptionPane editPane = new JOptionPane();
        JOptionPane confirmEdit = new JOptionPane();
        int ligne = TableauFormation.getSelectedRow();

        if (ligne > -1) {
            Formation f = tblf.getFormation(ligne);

            String n_nom = (String) editPane.showInputDialog(null, "Modifier le nom de la formation", "Modifier une formation", JOptionPane.QUESTION_MESSAGE, null, null, f.getNom());
            if (!n_nom.equals(f.getNom())) {
                f.setNom(n_nom);
                try {
                    FormationDao.update(f);
                    confirmEdit.showMessageDialog(null, "Formation " + n_nom + " modifiée", "Modifier une formation", JOptionPane.PLAIN_MESSAGE);
                    tblf.fireTableDataChanged();

                } catch (Exception ex) {
                    Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);

                }

            }
        }
    }//GEN-LAST:event_btnEditFormationActionPerformed

    private void btnAddFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFormationActionPerformed
        JOptionPane jp1 = new JOptionPane();
        JOptionPane jp2 = new JOptionPane();

        boolean formationAdded = false;

        while (!formationAdded) {
            btnDelFormation.setEnabled(false);
            btnEditFormation.setEnabled(false);

            String n_nom = jp1.showInputDialog(null, "Veuillez saisir le nom de la formation", "Ajouter une formation", JOptionPane.QUESTION_MESSAGE);
            if (n_nom.isEmpty()) {
                emptyFieldWarning("nom de la formation");
            } else {
                try {
                    Formation f = new Formation(n_nom);
                    FormationDao.create(f);

                    tblf.addFormation(f);
                    jp2.showMessageDialog(null, "Formation " + n_nom + " ajoutée", " Ajouter un stagiaire", JOptionPane.PLAIN_MESSAGE);
                    formationAdded = true;
                } catch (Exception ex) {
                    Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        }
    }//GEN-LAST:event_btnAddFormationActionPerformed

    private void btnCancelAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddStagiaireActionPerformed
        AddStagPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelAddStagiaireActionPerformed

    private void btnConfirmAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddStagiaireActionPerformed
        String s_prenom = textFieldAddPrenom.getText();
        String s_nom = textFieldAddNom.getText();
        Object s_form = comboAddStagiaire.getSelectedItem();

        Stagiaire s = new Stagiaire(0, s_nom, s_prenom, 0, (Formation) s_form);
        if (s_prenom.isEmpty() || s_nom.isEmpty()) {
            emptyFieldWarning("nom et prénom");
        } else {
            try {
                StagiaireDao.create(s);
                tbls.addStagiaire(s);
                textFieldAddPrenom.setText(null);
                textFieldAddNom.setText(null);

            } catch (Exception ex) {
                Logger.getLogger(Frame.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConfirmAddStagiaireActionPerformed

    private void btnDelFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelFormationActionPerformed
        int ligne = TableauFormation.getSelectedRow();
        Formation formation = tblf.getFormation(ligne);
        JOptionPane jp = new JOptionPane();

        int option = jp.showConfirmDialog(null, "Supprimer la formation \"" + formation + "\" ?", "Supprimer formation ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {

            if (ligne > -1) {
                Formation f = tblf.getFormation(ligne);
                try {
                    FormationDao.delete(f);
                    tblf.delFormation(f);
                    btnDelFormation.setEnabled(false);
                    btnEditFormation.setEnabled(false);

                } catch (Exception ex) {
                    Logger.getLogger(Frame.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_btnDelFormationActionPerformed

    private void btnDelStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStagiaireActionPerformed
        int ligne = TableauStagiaire.getSelectedRow();
        JOptionPane jp = new JOptionPane();
        Stagiaire stagiaire = tbls.getStagiaire(ligne);

        int option = jp.showConfirmDialog(null, "Supprimer \"" + stagiaire + "\" ?", "Supprimer stagiaire ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {

            if (ligne > -1) {
                Stagiaire s = tbls.getStagiaire(ligne);
                try {
                    StagiaireDao.delete(s);
                    tbls.delStagiaire(s);
                    btnEditStagiaire.setEnabled(false);
                    btnDelStagiaire.setEnabled(false);

                } catch (Exception ex) {
                    Logger.getLogger(Frame.class
                            .getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnDelStagiaireActionPerformed

    private void btnEraseAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseAddStagiaireActionPerformed
        textFieldAddPrenom.setText(null);
        textFieldAddNom.setText(null);
    }//GEN-LAST:event_btnEraseAddStagiaireActionPerformed

    private void comboAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAddStagiaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAddStagiaireActionPerformed

    private void textFieldAddNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAddNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAddNomActionPerformed

    private void textFieldAddPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAddPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAddPrenomActionPerformed

    private void btnEditStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStagiaireActionPerformed
        editStagPanel.setVisible(true);
    }//GEN-LAST:event_btnEditStagiaireActionPerformed

    private void textFieldEditPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEditPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEditPrenomActionPerformed

    private void btnCancelEditStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditStagiaireActionPerformed
        editStagPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelEditStagiaireActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
     try {
           JasperReport report = (JasperReport) JRLoader.loadObject(Frame.class.getClass().getResource("/reports/Flower.jasper"));
            //pour éviter l'import de fonts
            report.setProperty("net.sf.jasperreports.awt.ignore.missing.font", "false");
            report.setProperty("net.sf.jasperreports.default.font.name=SansSerif", "true");
            HashMap<String, Object> params = new HashMap<>();
            
            JasperPrint jPrint = JasperFillManager.fillReport(report, params, ConnectDb.getConnection());
            
            JFrame pdfFrame = new JFrame("Rapport");
            pdfFrame.getContentPane().add(new JRViewer(jPrint));
            pdfFrame.pack();
            pdfFrame.setSize(this.getSize());
            pdfFrame.setVisible(true);
        
        
        } catch (JRException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnEditEcfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEcfActionPerformed
        editEcfPanel.setVisible(true);
    }//GEN-LAST:event_btnEditEcfActionPerformed

    private void btnAddEcfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEcfActionPerformed
        addEcfPanel.setVisible(true);
    }//GEN-LAST:event_btnAddEcfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStagPanel;
    private javax.swing.JTable TableauFormation;
    private javax.swing.JTable TableauStagiaire;
    private javax.swing.JPanel addEcfPanel;
    private javax.swing.JButton btnAddEcf;
    private javax.swing.JButton btnAddFormation;
    private javax.swing.JButton btnAddStagiaire;
    private javax.swing.JButton btnCancelAddStagiaire;
    private javax.swing.JButton btnCancelEditStagiaire;
    private javax.swing.JButton btnConfirmAddStagiaire;
    private javax.swing.JButton btnConfirmEditStagiaire;
    private javax.swing.JButton btnDelEcf;
    private javax.swing.JButton btnDelFormation;
    private javax.swing.JButton btnDelStagiaire;
    private javax.swing.JButton btnEditEcf;
    private javax.swing.JButton btnEditFormation;
    private javax.swing.JButton btnEditStagiaire;
    private javax.swing.JButton btnEraseAddStagiaire;
    private javax.swing.JComboBox<Formation> comboAddStagiaire;
    private javax.swing.JComboBox<Formation> comboEditStagiaire;
    private javax.swing.JPanel editEcfPanel;
    private javax.swing.JPanel editStagPanel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField textFieldAddNom;
    private javax.swing.JTextField textFieldAddPrenom;
    private javax.swing.JTextField textFieldEditNom;
    private javax.swing.JTextField textFieldEditPrenom;
    // End of variables declaration//GEN-END:variables

}
